# Generated by Django 4.2.3 on 2023-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpuv', '0002_uservm'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservm',
            name='accountname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservm',
            name='accountpass',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmlist',
            name='ipaddr',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmlist',
            name='rootname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmlist',
            name='rootpass',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
